title: <p align="center"> Shristy Mall </p>
logo: /assets/img/DSC_5615.JPG

description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/shristy-mall/"> LinkedIn</a> |
  <a href="https://github.com/vishen-shristy">GitHub</a>


I'm working on Data Science, Big Data.
</p>


theme: jekyll-theme-minimal
